name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on: 
	push : 
		brancher: [main]
		
jobs:
	test-build:
		runs-on: ubuntu-latest
		
		strategy:
			matrix:
				node-version: [16.x]
		
		steps:
<<<<<<< HEAD
			- uses: actions/checkout@v2
			- name: Testing Build pre-Deploy
			  uses: actions/setup-node@v2
=======
			- uses: actions/checkout@v4
			- name: Testing Build pre-Deploy
			  uses: actions/setup-node@v4
>>>>>>> 641cc36441387539f5d09880dbad21d712e97be6
			  with:
				node-version: ${{ matrix.node-version }}
				cache: "npm"
			- run: npm i 
			- run: npm run build
